# Generated by Django 5.2 on 2025-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=5)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, choices=[('success', '✅ Success'), ('failed', '❌ Failed')], max_length=10, null=True)),
            ],
        ),
    ]
